package main

import (
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

// makeModule creates a temporary Go module with sub-packages described by
// pkgs (map[relativeDir]fileContent) and returns the root directory.
// If any package imports cxPkg, a local cx stub is created and a replace
// directive is added so go mod tidy succeeds without network access.
func makeModule(t *testing.T, modName string, pkgs map[string]string) string {
	t.Helper()
	root := t.TempDir()

	// Check if any source file imports the cx stub package.
	needsCxStub := false
	for _, src := range pkgs {
		if strings.Contains(src, cxPkg) {
			needsCxStub = true
			break
		}
	}

	// go.mod — add replace directive for the cx stub if needed.
	var gomod strings.Builder
	gomod.WriteString("module " + modName + "\n\ngo 1.21\n")
	if needsCxStub && modName != cxPkg {
		// Create a standalone cx stub module next to the test module.
		cxRoot := filepath.Join(filepath.Dir(root), "cxstub")
		if err := os.MkdirAll(cxRoot, 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(filepath.Join(cxRoot, "go.mod"),
			[]byte("module "+cxPkg+"\n\ngo 1.21\n"), 0o644); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(filepath.Join(cxRoot, "cx.go"),
			[]byte("package cx\n"), 0o644); err != nil {
			t.Fatal(err)
		}
		gomod.WriteString("\nrequire " + cxPkg + " v0.0.0\n")
		gomod.WriteString("replace " + cxPkg + " => " + cxRoot + "\n")
	}
	if err := os.WriteFile(filepath.Join(root, "go.mod"), []byte(gomod.String()), 0o644); err != nil {
		t.Fatal(err)
	}

	for rel, src := range pkgs {
		dir := filepath.Join(root, filepath.Dir(rel))
		if err := os.MkdirAll(dir, 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(filepath.Join(root, rel), []byte(src), 0o644); err != nil {
			t.Fatal(err)
		}
	}

	// Run go mod tidy so the module is valid for packages.Load.
	cmd := exec.Command("go", "mod", "tidy")
	cmd.Dir = root
	if out, err := cmd.CombinedOutput(); err != nil {
		t.Fatalf("go mod tidy: %v\n%s", err, out)
	}
	return root
}

// ---------------------------------------------------------------------------
// writeImports tests
// ---------------------------------------------------------------------------

func TestWriteImports_NoImports(t *testing.T) {
	out := filepath.Join(t.TempDir(), "out.go")
	if err := writeImports(out, "main", nil); err != nil {
		t.Fatal(err)
	}
	data, _ := os.ReadFile(out)
	content := string(data)
	if !strings.Contains(content, "package main") {
		t.Fatal("missing package declaration")
	}
	if strings.Contains(content, "import") {
		t.Fatal("should not contain import block when there are no imports")
	}
}

func TestWriteImports_WithImports(t *testing.T) {
	out := filepath.Join(t.TempDir(), "out.go")
	if err := writeImports(out, "mypkg", []string{"example.com/a", "example.com/b"}); err != nil {
		t.Fatal(err)
	}
	data, _ := os.ReadFile(out)
	content := string(data)
	if !strings.Contains(content, "package mypkg") {
		t.Fatal("wrong package name")
	}
	if !strings.Contains(content, `_ "example.com/a"`) {
		t.Fatal("missing import a")
	}
	if !strings.Contains(content, `_ "example.com/b"`) {
		t.Fatal("missing import b")
	}
	if !strings.Contains(content, "Code generated by cxgen") {
		t.Fatal("missing generated header")
	}
}

func TestWriteImports_CreatesDir(t *testing.T) {
	out := filepath.Join(t.TempDir(), "sub", "dir", "out.go")
	if err := writeImports(out, "main", nil); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(out); err != nil {
		t.Fatalf("output file not created: %v", err)
	}
}

// ---------------------------------------------------------------------------
// findProviders tests
// ---------------------------------------------------------------------------

const cxPkg = "example.com/cx"

func TestFindProviders_DetectsProvider(t *testing.T) {
	root := makeModule(t, "example.com/app", map[string]string{
		"svc/svc.go": `package svc

import _ "example.com/cx"

func init() {}
`,
	})
	providers, err := findProviders(root, "./...", cxPkg)
	if err != nil {
		t.Fatal(err)
	}
	if len(providers) != 1 || providers[0] != "example.com/app/svc" {
		t.Fatalf("want [example.com/app/svc], got %v", providers)
	}
}

func TestFindProviders_IgnoresNoInit(t *testing.T) {
	root := makeModule(t, "example.com/app", map[string]string{
		"svc/svc.go": `package svc

import _ "example.com/cx"
`,
	})
	providers, err := findProviders(root, "./...", cxPkg)
	if err != nil {
		t.Fatal(err)
	}
	if len(providers) != 0 {
		t.Fatalf("expected no providers, got %v", providers)
	}
}

func TestFindProviders_IgnoresNoCx(t *testing.T) {
	root := makeModule(t, "example.com/app", map[string]string{
		"svc/svc.go": `package svc

func init() {}
`,
	})
	providers, err := findProviders(root, "./...", cxPkg)
	if err != nil {
		t.Fatal(err)
	}
	if len(providers) != 0 {
		t.Fatalf("expected no providers, got %v", providers)
	}
}

func TestFindProviders_MultiplePackages(t *testing.T) {
	root := makeModule(t, "example.com/app", map[string]string{
		"a/a.go": `package a

import _ "example.com/cx"

func init() {}
`,
		"b/b.go": `package b

import _ "example.com/cx"

func init() {}
`,
	})
	providers, err := findProviders(root, "./...", cxPkg)
	if err != nil {
		t.Fatal(err)
	}
	if len(providers) != 2 {
		t.Fatalf("want 2 providers, got %v", providers)
	}
}

func TestFindProviders_SkipsCxPackageItself(t *testing.T) {
	root := makeModule(t, "example.com/cx", map[string]string{
		"cx.go": `package cx

func init() {}
`,
	})
	providers, err := findProviders(root, "./...", cxPkg)
	if err != nil {
		t.Fatal(err)
	}
	if len(providers) != 0 {
		t.Fatalf("cx package itself should be skipped, got %v", providers)
	}
}
