// cxgen scans a Go module for packages that self-register into a cx.Container
// via an init() function, then generates a Go source file containing the
// corresponding blank imports so that those init() calls are executed.
//
// A package is considered a provider when it:
//  1. Directly imports the cx package, AND
//  2. Declares a top-level init() function.
//
// Install:
//
//	go install github.com/kochabx/kit/cmd/cxgen@latest
//
// Typical go:generate directive in your main package:
//
//	//go:generate go run github.com/kochabx/kit/cmd/cxgen@latest gen -out cx_imports.go ./...
package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"os"
	"path/filepath"
	"sort"

	"github.com/spf13/cobra"
	"golang.org/x/tools/go/packages"
)

func main() {
	if err := rootCmd.Execute(); err != nil {
		os.Exit(1)
	}
}

var rootCmd = &cobra.Command{
	Use:   "cxgen",
	Short: "Code generator for cx container blank imports",
	Long: `cxgen scans a Go module for packages that import the cx container
and declare an init() function, then generates a file with blank imports
so those init() registrations are executed at startup.`,
}

var (
	flagOut string
	flagPkg string
	flagDir string
	flagCx  string
)

var genCmd = &cobra.Command{
	Use:   "gen [pattern]",
	Short: "Generate blank imports file",
	Long: `Scan packages matching pattern (default ./...) and write a Go source
file containing blank imports for every package that self-registers into
the cx container via init().`,
	Args: cobra.MaximumNArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		pattern := "./..."
		if len(args) > 0 {
			pattern = args[0]
		}

		providers, err := findProviders(flagDir, pattern, flagCx)
		if err != nil {
			return fmt.Errorf("scan: %w", err)
		}

		pkgName := flagPkg
		if pkgName == "" {
			pkgName = inferPkg(flagOut)
		}

		if err := writeImports(flagOut, pkgName, providers); err != nil {
			return fmt.Errorf("write: %w", err)
		}
		cmd.Printf("wrote %d blank import(s) → %s\n", len(providers), flagOut)
		return nil
	},
}

func init() {
	genCmd.Flags().StringVarP(&flagOut, "out", "o", "cx_imports.go", "output file path")
	genCmd.Flags().StringVarP(&flagPkg, "pkg", "p", "", "package name for the output file (default: inferred from -out directory)")
	genCmd.Flags().StringVarP(&flagDir, "dir", "d", ".", "directory to scan (module root)")
	genCmd.Flags().StringVar(&flagCx, "cx", "github.com/kochabx/kit/cx", "import path of the cx package")

	rootCmd.AddCommand(genCmd)
}

// findProviders loads all packages matching pattern under dir and returns the
// import paths of packages that both import the cx package and declare an
// init() function — the canonical self-registration pattern.
func findProviders(dir, pattern, cxPkgPath string) ([]string, error) {
	cfg := &packages.Config{
		Mode: packages.NeedName |
			packages.NeedFiles |
			packages.NeedImports |
			packages.NeedSyntax,
		Dir: dir,
	}
	pkgs, err := packages.Load(cfg, pattern)
	if err != nil {
		return nil, fmt.Errorf("load packages: %w", err)
	}

	for _, pkg := range pkgs {
		for _, e := range pkg.Errors {
			// Non-fatal: report but continue — partial results are still useful.
			_, _ = fmt.Fprintf(os.Stderr, "cxgen: warning: %s\n", e.Msg)
		}
	}

	var providers []string
	for _, pkg := range pkgs {
		if pkg.PkgPath == cxPkgPath {
			continue // skip the cx package itself
		}
		if !importsCx(pkg, cxPkgPath) {
			continue
		}
		if hasInit(pkg) {
			providers = append(providers, pkg.PkgPath)
		}
	}
	sort.Strings(providers)
	return providers, nil
}

// importsCx reports whether pkg directly imports cxPkgPath.
func importsCx(pkg *packages.Package, cxPkgPath string) bool {
	_, ok := pkg.Imports[cxPkgPath]
	return ok
}

// hasInit reports whether any file in pkg declares a top-level init() function.
func hasInit(pkg *packages.Package) bool {
	for _, f := range pkg.Syntax {
		for _, decl := range f.Decls {
			fn, ok := decl.(*ast.FuncDecl)
			if ok && fn.Recv == nil && fn.Name.Name == "init" {
				return true
			}
		}
	}
	return false
}

// inferPkg guesses the package name for outFile by loading the package in its
// directory. Falls back to the directory's base name.
func inferPkg(outFile string) string {
	outAbs, err := filepath.Abs(outFile)
	if err != nil {
		return "main"
	}
	outDir := filepath.Dir(outAbs)

	cfg := &packages.Config{
		Mode: packages.NeedName,
		Dir:  outDir,
	}
	pkgs, err := packages.Load(cfg, ".")
	if err != nil || len(pkgs) == 0 || pkgs[0].Name == "" {
		return filepath.Base(outDir)
	}
	return pkgs[0].Name
}

// writeImports generates and writes the output file containing blank imports.
func writeImports(outFile, pkgName string, importPaths []string) error {
	var buf bytes.Buffer
	buf.WriteString("// Code generated by cxgen. DO NOT EDIT.\n\n")
	fmt.Fprintf(&buf, "package %s\n", pkgName)

	if len(importPaths) > 0 {
		buf.WriteString("\nimport (\n")
		for _, p := range importPaths {
			fmt.Fprintf(&buf, "\t_ %q\n", p)
		}
		buf.WriteString(")\n")
	}

	src, err := format.Source(buf.Bytes())
	if err != nil {
		// Write raw bytes so the user can debug the generated source.
		src = buf.Bytes()
	}

	if dir := filepath.Dir(outFile); dir != "" && dir != "." {
		if err := os.MkdirAll(dir, 0o755); err != nil {
			return fmt.Errorf("mkdir %s: %w", dir, err)
		}
	}
	return os.WriteFile(outFile, src, 0o644)
}
